version: 0.2

env:
  variables:
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

phases:
  install:
    commands:
      - apt-get update -y
  pre_build:
    commands:
      - echo Nothing to do in pre_build
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR && npm install

artifacts:
  files:
    - $CODEBUILD_SRC_DIR/*