version: 0.2

env:
  variables:
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

phases:
  install:
    commands:
      - echo Install Phase
  pre_build:
    commands:
      - echo Prebuild Phase
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR && npm install